% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{tabularray}
\usepackage[normalem]{ulem}
\usepackage{graphicx}
\usepackage{rotating}
\UseTblrLibrary{booktabs}
\UseTblrLibrary{siunitx}
\NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
\newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
\newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Ass2MSB104GRP3},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Ass2MSB104GRP3}
\author{}
\date{}

\begin{document}
\maketitle


\section{Del A: Vekst og Ulikhet}\label{del-a-vekst-og-ulikhet}

I Lessmann (2017) sin tekst vil effekten man vil forvente å se på GINI
koefisienten avhenge om regionen man ser på er rik eller fattig fra før.
I rikere land forventer man en negativ sammenheng mellom vekst og
ulikhet, dvs at vekst fører til reduserte ulikheter mellom regioner.
Dette kommer av at i rikere land er vil i stor grad de rike regionene
være såpass velstående at verdiøkningen ønskes sentrert i de områdene
som er underuviklet sett i sammenheng med resten av landet. I fattigere
regioner forventer man på den andre siden å se en positiv sammenheng
mellom vekst og ulikhet. Dette kalles ``kuznets'' effekten. Ettersom
regresjonsanalysen ga en positiv ß1 verdi, burde det etter kuznets
effekten indikere at datasettets inneholder mest regioner med lavere
velstand relativt sett.

\subsection{Model Diagnostikk}\label{model-diagnostikk}

\begin{table}
\centering
\begin{talltblr}[         %% tabularray outer open
caption={Enkel regresjonsmodel. {#tbl-reg1}},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]},
column{2}={}{halign=c,},
column{1}={}{halign=l,},
hline{6}={1-2}{solid, black, 0.05em},
}                     %% tabularray inner close
\toprule
& Model 1: GINI ~ Vekst \\ \midrule %% TinyTableHeader
(Intercept) & 0.044 \\
& (0.012) \\
vekst & 0.538 \\
& (0.160) \\
Num.Obs. & 29 \\
R2 & 0.295 \\
R2 Adj. & 0.269 \\
RMSE & 0.04 \\
\bottomrule
\end{talltblr}
\end{table}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1622}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2838}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1757}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1081}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1081}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1622}}@{}}
\caption{Regresjonsresultater for modellen}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variabel
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Estimert koeffisient
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Standardfeil
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
t-verdi
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p-verdi
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Signifikans
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variabel
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Estimert koeffisient
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Standardfeil
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
t-verdi
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p-verdi
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Signifikans
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 0.0441 & 0.0116 & 3.7920 & 0.0008 & *** \\
vekst & 0.5383 & 0.1602 & 3.3614 & 0.0023 & ** \\
\end{longtable}

I funksjonen over fremkommer analysegrunnlaget som skal brukes i
regresjons modellen. Vekst er sattt som uavhengi variabel, og GINI
koefisienten som avhengi variabel. Med dette datasettet kan vi teste
Lessmann (2017) sin teori om at det er en sammenheng mellom økonomisk
vekst of ulikhet.

Resultatene fra den enkle lineære regresjonsmodellen (se
\textbf{?@tbl-reg1}) viser at økonomisk vekst (Vekst) har en positiv og
statistisk signifikant sammenheng med regional ulikhet (GINI) på
NUTS2-nivå i 2017. Koeffisienten til vekst (β₁ = 0.538, SE = 0.160)
indikerer at regioner med høyere vekst i BNP per innbygger også har
høyere grad av ulikhet. Dette funnet peker mot et mønster av regional
divergens, hvor økonomisk vekst i større grad samles i allerede
velstående regioner.

Modellens konstantledd (β₀ = 0.044) representerer forventet ulikhet i
regioner uten økonomisk vekst, altså et GINI-nivå på rundt 0.044.

\begin{longtable}[]{@{}lr@{}}
\caption{Goodness-of-fit statistikk for modellen}\tabularnewline
\toprule\noalign{}
Statistikk & Verdi \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Statistikk & Verdi \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
R-squared & 0.295000 \\
Adjusted R-squared & 0.268900 \\
Residual Standard Error & 0.039600 \\
F-statistic & 11.300000 \\
F-statistic p-verdi & 0.002329 \\
\end{longtable}

Forklaringskraften er moderat (R² = 0.295, justert R² = 0.269), noe som
innebærer at omtrent 30 \% av variasjonen i ulikhet kan forklares av
vekstforskjeller mellom regionene. Resten av variasjonene må tilskrives
andre faktorer som ikke inngår i denne modellen. Disse variablene kan
for eksempel være utdanning, demografi og eller næringsstruktur.
Residualstandardfeilen (RMSE ≈ 0.04) viser at modellens prediksjoner har
relativ små avvik fra observerte verdier.

Vider så kan vi se på F statistikken for å finne ut av hvor sannsynlig
det for at variablene er signifikante. I vår regresjonsmodell kommer det
frem en F-statistikk på 11.3 og en p-verdi på 0.0023. F-statistikk på
11.3 er ganske høyt, noe som betyr at variasjonen forklart av modellen
er betydelig større enn det man forventer fra tilfeldigheter. En p-verdi
på 0.0023 betyr at det er en 0.23\% sannsynlighet for å få et så sterkt
resultat dersom det ikke finnes en sammenheng mellom variablene. Dersom
vi bruker en vanlig signifikansnivå 5\%, så er 0.0023 mye lavere enn
0.05, altså kan vi forkaste nullhypotesen (altså at det ikke er noen
effekt eller sammenheng)

\subsubsection{OLS-forutsetninger og
vurderinger}\label{ols-forutsetninger-og-vurderinger}

Den klassiske OLS-modellen bygger på fem sentrale forutsetninger for at
estimatene skal være upartiske og effektive.

Den første forutsetningen er \textbf{Lineæritet:} Dette går ut på at
forholdet mellom ulikhet (Gini) og de uavhengige variablene antas å være
lineært. Residualplott viser ingen klare mønstre, noe som tyder på at
antakelsen holder. Ved brudd på denne forutsetningen kan det være nytt å
benytte transformasjoner eller ikke-lineære modeller.

Videre har vi forutsetningen om \textbf{Uavhengighet:} I vårt datasett
representerer observasjonene ulike regioner, og det kan være rimelig å
anta at de fleste regionene er uavhengige. Dersom enkelte regioner er
geografisk eller økonomisk tilknyttet, kan dette skape korrelasjon
mellom residualene. En konsekvens av dette er feil standardfeil og
misvisende signifikansnivåer. Dette kan håndteres ved å bruke
cluster-robuste standardfeil.

OLS forutsetter at variansen til feilleddene er konstant
(\textbf{homoskedastisk}). I praksis viser økonomiske data ofte
heteroskedastisitet, spesielt mellom regioner med ulik størrelse eller
inntektsnivå. Hvis denne forutsetningen brytes, påvirkes ikke
koeffisientene, men standardfeilene blir feilberegnet og hypotesetester
blir upålitelige. Løsningen er å bruke robuste standardfeil (HC) eller
log-transformasjoner av variabler.

\textbf{Multikolinaritet:} Forklaringsvariablene skal ikke være perfekt
korrelert. En korrelasjonsanalyse viser moderat sammenheng mellom
utdanning og arbeidsledighet, men ikke nok til å skape problemer. Ved
alvorlig multikollinearitet øker standardfeilene, og det blir vanskelig
å identifisere individuelle effekter. Tiltak kan være å fjerne
overlappende variabler eller bruke hovedkomponentanalyse (PCA).

Forutsetningen om \textbf{normalfordelte} feilledd er sentralt for at
t-tester og konfidensintervaller skal være gyldige. Residualplottet
viser at residualene i modellen følger en tilnærmet normal fordeling,
selv om et mindre utvalg (N = 29) naturlig kan gi enkelte avvik. Dersom
normalitetsantakelsen ikke holder, kan bootstrapping benyttes for å
oppnå mer robuste og pålitelige standardfeil.

De fleste OLS-forutsetningene ser ut til å være rimelig oppfylt i denne
modellen. Noe heteroskedastisitet og svak multikollinearitet kan være
til stede, men dette kan håndteres ved bruk av robuste standardfeil.
Samlet sett vurderes modellen som rimelig robust, selv om bruk av
robuste standardfeil og kontroll for regionale sammenhenger kan forbedre
påliteligheten.

\subsection{Visualisering}\label{visualisering}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{ass2msb104grp3_files/figure-pdf/fig-gini-growth-1.pdf}}

}

\caption{\label{fig-gini-growth}Sammenheng mellom regional ulikhet (målt
ved Gini-koeffisienten) og økonomisk vekst i BNP per innbygger for
NUTS2-regioner i 2017. Figuren viser en positiv sammenheng, hvor
regioner med høyere veksttakt også tenderer til å ha høyere
inntektsulikhet. Den røde linjen representerer estimert lineær regresjon
med 95 \% konfidensintervall (grått felt).}

\end{figure}%

\section{Del B: Utforsker andre determinanter for
ulikhet}\label{del-b-utforsker-andre-determinanter-for-ulikhet}

\subsection{Part B: Andre variabler som påvirker
ulikhet}\label{part-b-andre-variabler-som-puxe5virker-ulikhet}

\subsection{Data Tilhenting}\label{data-tilhenting}

\begin{longtable}[]{@{}lllll@{}}
\caption{Regresjonsresultater for modell med Gini som avhengig variabel
(2017)}\tabularnewline
\toprule\noalign{}
term & Estimate & Std. Error & t value &
Pr(\textgreater\textbar t\textbar) \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
term & Estimate & Std. Error & t value &
Pr(\textgreater\textbar t\textbar) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
(Intercept) & 0.1074 & 0.0373 & 2.8764 & 0.0083 \\
vekst & 0.3792 & 0.1986 & 1.9095 & 0.0682 \\
arbeidsledighet & -0.0024 & 0.0018 & -1.3669 & 0.1843 \\
bpk & 0.000022 & 0.0000 & 0.7026 & 0.4890 \\
hoyere\_utdanning & -0.0017 & 0.0010 & -1.6404 & 0.1140 \\
\end{longtable}

\subsection{Valg av variabler}\label{valg-av-variabler}

Det er hentet inn 3 nye datasett som kan være med å forklare ulikhet
mellom regioner. Som det kom frem i del A gir modell
@ref(tab:passelighet) oss en forklaringskraft på ca 29\%. Det er derfor
intressant å utvide modellen for å fange opp flere årsaker til ulikhet,
samt å se hvor relavante andre variabler kan være. Dataene som tilføyes
er arbeidsledighet, og befolkningstethet. Etter metadataene kommer det
frem at det er populasjonen i alderen mellom 15 og 74 år som er tatt med
i datasettet.

Arbeidsledighet er målt i prosent, og sier hvor stor andel av
befolkningen innenfor NUTS2 regionene som er arbeidsledige.
Arbeidsledighet er en vanlig indikatorene som benyttes for å vurdere
regionale økonomiske tilstander. Variablen sier noe om hvor god tilgang
det er på arbeidsmuligheter i regionen. Dersom en region har høy
arbeidsledighet, er det mangel på økonokiske muligheter til
befolkningen, som gir en økt inntektsulikhet. Det forventes derfor at
det er en positiv korelasjon mellom arbeidsledighet og ulikhet.

Befolkningstetthet måler hvor mange innbyggere en region har per
kvadratkilometer. Dette er en indikator på hvor urbane de ulike
regionene er. Områder med høy tetthet kan kalles for byområder, mens de
med lav faller innenfor forstadene. I mange land, for eksempel Norge er
det typisk at industriend sentrer seg rundt byområder, hvor det er bedre
tilgang på utdanning og et bredere spektrum av arbeidsmuligheter.

Utdanningsnivå måles som andelen av befolkningen som har en høyere
utdanning. I dette datasettet har vi filtrert og definert høyere
utdanning ved koden ED5-8. ED5-8 er altså tertiær utdanning, som
omfatter Bachelorgrad (ED5), Mastergrad (ED7) og Doktorgrad (ED8). Et
høyt utdanningsnivå bidrar til økt produktivitet, innovasjon og høyere
inntekstnivå, som kan redusere ulikhet gjennom bedre arbeidsmuligheter.
Samtidig kan forskjeller i utdanning mellom regioner føre til en økende
ulikhet dersom utdanning og kompetanse i hovedsak er konsentrert i
urbane eller økonomisk sterke områder. Utdanning kan dermed føre til
både muligheten for konvergens og risikoen for regional divergens.

\begin{verbatim}
R-squared:  0.3924 
\end{verbatim}

\begin{verbatim}
Adjusted R-squared:  0.2911 
\end{verbatim}

\begin{verbatim}
F-statistic:  3.87  on  4  and  24  DF
\end{verbatim}

\begin{verbatim}
Model p-value (F-test):  0.01447 
\end{verbatim}

Tabell 2 og 3 viser resultatene fra vår multippel regresjonsmodell
hvorregional ulikhet (målt ved Gini-koeffisienten) forklares av
økonomisk vekst (BNPPI\_vekst), arbeidsledighet, befolkning (bpk) og
høyere utdanning.

Konstantleddet (intercept) på 0.107 indikerer at den forventede
Gini-verdien i en region er omtrent 0.107 når alle forklaringsvariabler
er lik null.

Koeffisienten til \textbf{BNPPI\_vekst} (0.0038) er positiv og svakt
signifikant (p = 0.068), noe som indikerer at regioner med høyere
økonomisk vekst har en tendens til å oppleve økt inntektsulikhet. Dette
kan tolkes som at gevinsten av økonomisk vekst i stor grad tilfaller
bestemte deler av befolkningen, særlig de med høyere inntekt eller
kapital, før fordelene på lengre sikt eventuelt fordeles jevnere.

\textbf{Arbeidsledighet} (-0.0024) har en negativ, men ikke-signifikant
effekt (p = 0.184). Dette kan tyde på at høyere arbeidsledighet isolert
sett ikke er en sterk forklaringsfaktor i denne modellen, men retningen
er som forventet -- lavere sysselsetting øker normalt ulikhet.

Variabelen \textbf{bpk} (0.000022) viser en svært svak og statistisk
ubetydelig sammenheng (p = 0.49), noe som indikerer at
befolkningsstørrelse eller -tetthet i seg selv ikke forklarer mye av
ulikhetsnivået mellom regionene.

Til slutt viser høyere utdanning (-0.0017) en negativ, men
ikke-signifikant sammenheng med regional ulikhet (p = 0.114). Dette
tyder på at regioner med høyere utdanningsnivå i gjennomsnitt har lavere
ulikhet, noe som er i tråd med teorien om at utdanning styrker
humankapitalen og bidrar til sosial mobilitet.

\textbf{Modellens forklaringskraft} R\^{}2 = 0.392 og justert R\^{}2 =
0.291 viser at modellen viser om lag 39\% av variasjonen i regional
ulikhet. F-testen (p = 0.014) indikerer at modellen samlet sett er
signifikant, selv om enkelte variabler ikke er det individuelt. Dette
betyr at forklaringsvariablene sammen bidrar til å forklare
ulikhetsnivået på tvers av NUTS2-regionene. Samlet sett antyder
resultatene at økonomisk vekst og utdanningsnivå spiller de viktigste
rollene i å forklare ulikhet, mens arbeidsledighet og befolkningstetthet
har svakere eller mer indirekte effekter.

\section{Del C: Dokumentasjon for bruken av
KI}\label{del-c-dokumentasjon-for-bruken-av-ki}

Vi har benyttes oss av Chat-gpt5 og Chat-gpt3. I denne oppgaven vi brukt
KI til å først og fremst forstå og tolke hva oppgaven spør etter. Når vi
har hatt knote feil med kode har vi benytt chat-gpt for å få hjelpende
hånd i riktig retning. Vi har også brukt det til hjelp for å analysere
dataeien og til å formulere teori delen på en bedre måte.

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-lessmann2017}
Lessmann, Christian. 2017. {``Regional Inequality, Convergence, and Its
Determinants {\textendash} a View from Outer Space☆.''} \emph{European
Economic Review}, 23.

\end{CSLReferences}




\end{document}
