---
title: "Assignment 1"
format: html
editor: visual
---

## 

```{r}
library(modelr)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(vtable)
library(flextable)
library(scales)
library(tinytex)
library(readxl)
```

```{r}
Sys.setlocale("LC_ALL", "Norwegian")
```

```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(janitor)


# Les inn DEMO som character
demo <- read_excel("DEMO_Ass1.xlsx", sheet = 2, col_types = "text") %>%
  clean_names()

# Les inn GDP som character
gdp <- read_excel("GDP_Ass1.xlsx", sheet = 2, col_types = "text") %>%
  clean_names()


```

```{r}
# ---- Gjør begge "long" ----
demo_long <- demo %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "time",
    values_to = "population"
  ) %>%
  mutate(
    time = as.integer(str_remove(time, "^x")),
    population = as.numeric(population)
  )

gdp_long <- gdp %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "time",
    values_to = "gdp"
  ) %>%
  mutate(
    time = as.integer(str_remove(time, "^x")),
    gdp = as.numeric(gdp)
  )

```

```{r}
# Beregne GDP per innbygger 
combined <- demo_long %>%
  left_join(gdp_long, by = join_by(region, time)) %>%
  mutate(gdp_per_capita = gdp / population* 1000000)
  
```
